{{- if and .Values.cert.isCertEnabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "name" . }}
spec:
  secretName: {{ template "name" . }}-tls
  issuerRef:
    name: {{ .Values.cert.issuerName }}
    kind: {{ .Values.cert.issueType }}
  commonName: {{ .Values.cert.dns }}
  acme:
    config:
    - dns01:
        provider: {{ .Values.cert.provider }}
      domains:
      - {{ .Values.cert.dns }}
{{- end }}
